### ISSUE TITLE
Where are the Dockerfiles for the speechmodels images ?

### ISSUE THREAD

**Issue by fabito** [danijel3/SpeechToolsWorkers#5]
Hi @danijel3 ,

First of all, thanks for these great docker images and utility tools, very useful!
I was trying to understand the difference between the different flavors: `studio`, `sejm` and `pkf` but couldn't find the respective `Dockerfiles`. 
Where are they ? Are thy on github ?

Thanks

**Comment by danijel3** [comment]
Hey, I'm actually surprised you fount this project. It's a back-end for our project website. The website isn't too crowded, so I'm not really super worried about performance, but if you were to do it properly, you'd probably use something like Kafka and Kubernetes. I intend to make it much more simple and even dump Rabbitmq for a simple Mongo mechanic (as per [this blogpost](https://blog.serverdensity.com/replacing-rabbitmq-with-mongodb/)).

That being said, it's a good question about the models. I don't have dockerfiles here, because the models themselves are too big to dump on github. Each dockerfile looks something like this:
```
FROM danijel3/kaldi
MAINTAINER Danijel Koržinek <danijel@pja.edu.pl>

COPY studio /dist/model/studio

RUN ln -s /dist/model/studio /dist/model/default

ENTRYPOINT ["/bin/bash","-c"]
```

Where `studio` contains ~2GB worth of models. The reason I decided to do it that way is to abuse the dockerhub system as a cheap alternative to distribute large models. In practice, this is quite annoying and it's a much better idea to simply mount the model dirs using the `-v` switch and I think I'll do it this way. I'll distribute the models from our website and create a script to download the model from the common repository.

**Comment by fabito** [comment]
Which of the versions contains all the necessary models for the `SpeakerDiarization/run.sh` ? I'm asking this because the `studio` version is 2G, I was wondering if I could make it smaller or use one of the others.

**Comment by fabito** [comment]
Just a little bit of context. I'm building a separate app written in go which exposes the `SpeakerDiarization/run.sh` as an http endpoint. The new docker image is based on `studio`. I have a working prototype and now I'll try to make the image smaller.

**Comment by danijel3** [comment]
Each version contains all the models for all the tools. Studio is studio based speech, Sejm is parliamentary speech and PKF is very old broadcast TV.

The speaker diarization is actually based on this: http://kaldi-asr.org/models/m6

I didn't train it or anything as it is generally considered a language independent problem. I suppose I should retrain in on some 16k data, but that's not that big of an issue for now. The Callhome model works pretty well (better than LIUM in any case).

**Comment by danijel3** [comment]
Yea, you don't need any of the model images for diarization only. Everything is available on Github.
